apiVersion: v1
kind: Service
metadata:
  name: devops-exercise 
  namespace: devops-exercise
spec:
  type: NodePort
  selector:
    app: devops-exercise
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
status:
  loadBalancer: {}

